<a href="https://colab.research.google.com/github/yoo9519-AIdev/Learning/blob/master/20200713.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

둘 사이간의 어떤 유사도를 알고싶을 때
 - 유클리디안 거리, 코사인 유사도 함수 활용
 - 자카드 유사도 : 집합을 통해서 토큰화
 - 사과와 원숭이의 유사도를 코사인 유사도, 유클리디안 거리를 활용해서 구분하자

In [ ]:
word_embedding_dic = {'사과': [1.0, 0.5],
                     '바나나': [0.9, 1.2],
                     '원숭이': [0.5, 1.0]
                     }

In [ ]:
import numpy as np
def euclidean_dist(x, y):
    x = np.array(x)
    y = np.array(y)

    return np.sqrt(np.sum(x-y)**2)

euclidean_dist(word_embedding_dic['사과'], word_embedding_dic['바나나'])

0.6

In [ ]:
def cosine_similarity(x, y):
    nominator = np.dot(x, y)
    denominator = np.linalg.norm(x) * np.linalg.norm(y)
    
    return nominator/denominator

token_s1 = s1.split()  
 ex) 대부분 원숭이는 바나나를 좋아합니다.  
token_s2 = s2.split()  
 ex) 코주부 원숭이는 바나나를 싫어합니다.  
 
union = set(token_s1).union ~

문서의 표현
 - bow 생성 방법
  - 각 토큰에 고유 인덱스 부여
  - 각 인덱스 위치에 토큰 등장 횟수를 기록
 - 한계 : 단어의 순서를 고려하지 않음

In [ ]:
pip install kss

Note: you may need to restart the kernel to use updated packages.


In [ ]:
import pandas as pd
docs = '오늘 커피를 마셨어. 오늘 아메리카노를 마셨어. 오늘 마셨어 마셨어. 커피 커피 마셨어.'

In [ ]:
import kss
print(kss.split_sentences(docs))

['오늘 커피를 마셨어.', '오늘 아메리카노를 마셨어.', '오늘 마셨어 마셨어.', '커피 커피 마셨어.']


Bow 생성방법으로 default 설정해서 해결해보기

In [ ]:
docs = ['오늘 동물원에서 원숭이를 봤어',
        '오늘 동물원에서 코끼리를 봤어 봤어',
        '동물원에서 원숭이에게 바나나를 줬어 바나나를']

In [ ]:
word_list = []
for doc in docs:
    word_list.extend(doc.split())
    
word_list

['오늘',
 '동물원에서',
 '원숭이를',
 '봤어',
 '오늘',
 '동물원에서',
 '코끼리를',
 '봤어',
 '봤어',
 '동물원에서',
 '원숭이에게',
 '바나나를',
 '줬어',
 '바나나를']

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
docs

['오늘 동물원에서 원숭이를 봤어', '오늘 동물원에서 코끼리를 봤어 봤어', '동물원에서 원숭이에게 바나나를 줬어 바나나를']

In [ ]:
vector = CountVectorizer()
print(vector.fit_transform(docs).toarray())
print(vector.vocabulary_)

[[1 0 1 1 1 0 0 0]
 [1 0 2 1 0 0 0 1]
 [1 2 0 0 0 1 1 0]]
{'오늘': 3, '동물원에서': 0, '원숭이를': 4, '봤어': 2, '코끼리를': 7, '원숭이에게': 5, '바나나를': 1, '줬어': 6}


복습내용
 - Tokenization
 - Bow
 - CounterVectorizer
 - 코사인, 유클리드 벡터
 - OneHotEncoding

In [ ]:
word_ls = ['원숭이', '바나나', '사과', '사과']

In [ ]:
word_dict = {} # {원숭이:0, 바나나:1, 사과:2}

In [ ]:
# 이 방법도 있고
index = 0
for word in word_ls:
    if word not in word_dict.keys():
        word_dict[word] = index
        index += 1
    
word_dict

{'원숭이': 0, '바나나': 1, '사과': 2}

In [ ]:
# 이 방법도 있다.
from collections import defaultdict # 알아서 생성할 때, 값을 주게 된다.

word2index = defaultdict(lambda:len(word2index))
for word in word_ls:
    word2index[word]
    
word2index

defaultdict(<function __main__.<lambda>()>, {'원숭이': 0, '바나나': 1, '사과': 2})

In [ ]:
# 이 방법도 있다.
vector = CountVectorizer()
print(vector.fit_transform(word_ls).toarray())
print(vector.vocabulary_)

[[0 0 1]
 [1 0 0]
 [0 1 0]
 [0 1 0]]
{'원숭이': 2, '바나나': 0, '사과': 1}


In [ ]:
unique_word_size = len(word2index)
one_hot_vectors = np.zeros((len(word_ls), unique_word_size))
one_hot_vectors

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
text = "Don't be fooled by the dark sounding name, Mr. Jone's Orphanage is as cheery as cheery goes for a pastry shop."

In [ ]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /Users/yoo/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [ ]:
from nltk.tokenize import word_tokenize
print(word_tokenize(text))

['Do', "n't", 'be', 'fooled', 'by', 'the', 'dark', 'sounding', 'name', ',', 'Mr.', 'Jone', "'s", 'Orphanage', 'is', 'as', 'cheery', 'as', 'cheery', 'goes', 'for', 'a', 'pastry', 'shop', '.']


In [ ]:
texts = ['오늘 동물원에서 원숭이를 봤어',
        '오늘 동물원에서 코끼리를 봤어 봤어',
        '동물원에서 원숭이에게 바나나를 줬어 바나나를']

In [ ]:
open = []
for text in texts:
    open.extend(text.split())
    
open

['오늘',
 '동물원에서',
 '원숭이를',
 '봤어',
 '오늘',
 '동물원에서',
 '코끼리를',
 '봤어',
 '봤어',
 '동물원에서',
 '원숭이에게',
 '바나나를',
 '줬어',
 '바나나를']

In [ ]:
open = list(set(open))
open

['줬어', '봤어', '코끼리를', '원숭이에게', '바나나를', '오늘', '동물원에서', '원숭이를']

In [ ]:
for i in enumerate(open):
    print(i)

(0, '줬어')
(1, '봤어')
(2, '코끼리를')
(3, '원숭이에게')
(4, '바나나를')
(5, '오늘')
(6, '동물원에서')
(7, '원숭이를')


In [ ]:
ls =np.array([i for i in enumerate(open)])
ls

array([['0', '줬어'],
       ['1', '봤어'],
       ['2', '코끼리를'],
       ['3', '원숭이에게'],
       ['4', '바나나를'],
       ['5', '오늘'],
       ['6', '동물원에서'],
       ['7', '원숭이를']], dtype='<U21')

In [ ]:
open.

SyntaxError: invalid syntax (<ipython-input-266-e15e95c957a7>, line 1)

In [ ]:
# 이 방법도 있다.
vector = CountVectorizer()
print(vector.fit_transform(open).toarray())
print(vector.vocabulary_)

[[0 0 0 0 0 0 1 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 1 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0]]
{'줬어': 6, '봤어': 2, '코끼리를': 7, '원숭이에게': 5, '바나나를': 1, '오늘': 3, '동물원에서': 0, '원숭이를': 4}


In [ ]:
lss = vector.fit_transform(open).toarray()
print(vector.vocabulary_)
print(lss)

{'줬어': 6, '봤어': 2, '코끼리를': 7, '원숭이에게': 5, '바나나를': 1, '오늘': 3, '동물원에서': 0, '원숭이를': 4}
[[0 0 0 0 0 0 1 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 1 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0]]


In [ ]:
for i, v in enumerate(open):
    print("index : {}, value : {}".format(i, v))

index : 0, value : 줬어
index : 1, value : 봤어
index : 2, value : 코끼리를
index : 3, value : 원숭이에게
index : 4, value : 바나나를
index : 5, value : 오늘
index : 6, value : 동물원에서
index : 7, value : 원숭이를


In [ ]:
from nltk.tokenize import TreebankWordTokenizer
tokenizer = TreebankWordTokenizer()

text = "Starting a home-based restaurant may be an ideal. it doesn't have a food chain or restaurant of their own."
print(tokenizer.tokenize(text))

['Starting', 'a', 'home-based', 'restaurant', 'may', 'be', 'an', 'ideal.', 'it', 'does', "n't", 'have', 'a', 'food', 'chain', 'or', 'restaurant', 'of', 'their', 'own', '.']


In [ ]:
from nltk.tokenize import sent_tokenize
print(sent_tokenize(text))

['Starting a home-based restaurant may be an ideal.', "it doesn't have a food chain or restaurant of their own."]


In [ ]:
text2 = "I am actively looking for Ph.D. students. and you are a Ph.D student."
print(sent_tokenize(text2)) # 온점으로 구분하지는 않는다.

['I am actively looking for Ph.D. students.', 'and you are a Ph.D student.']


In [ ]:
import kss

In [ ]:
text3 = '딥 러닝 자연어 처리가 재미있기는 합니다. 그런데 문제는 영어보다 한국어로 할 때 너무 어려워요. 농담아니에요. 이제 해보면 알걸요?'
print(kss.split_sentences(text3)) # 정상적으로 분리된다.

['딥 러닝 자연어 처리가 재미있기는 합니다.', '그런데 문제는 영어보다 한국어로 할 때 너무 어려워요.', '농담아니에요.', '이제 해보면 알걸요?']


In [ ]:
from nltk.tokenize import word_tokenize
text = "I am actively looking for Ph.D. students. and you are a Ph.D. student."
print(word_tokenize(text))

['I', 'am', 'actively', 'looking', 'for', 'Ph.D.', 'students', '.', 'and', 'you', 'are', 'a', 'Ph.D.', 'student', '.']


In [ ]:
import nltk
nltk.download('averaged_perceptron_tagger')

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /Users/yoo/nltk_data...
[nltk_data] Error downloading 'averaged_perceptron_tagger' from
[nltk_data]     <https://raw.githubusercontent.com/nltk/nltk_data/gh-p
[nltk_data]     ages/packages/taggers/averaged_perceptron_tagger.zip>:
[nltk_data]     HTTP Error 500: Internal Server Error


False